# Generated by Django 5.1.2 on 2024-10-29 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BodyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0.0, help_text='身高（公分）')),
                ('weight', models.FloatField(default=0.0, help_text='體重（公斤）')),
                ('body_fat_percentage', models.FloatField(default=0.0, help_text='體脂率（百分比）')),
                ('muscle_mass', models.FloatField(default=0.0, help_text='肌肉量（公斤）')),
                ('bmi', models.FloatField(blank=True, default=0.0, help_text='身體質量指數', null=True)),
                ('visceral_fat', models.FloatField(default=0.0, help_text='內臟脂肪等級')),
                ('basal_metabolic_rate', models.IntegerField(blank=True, help_text='基礎代謝率 (kcal/day)', null=True)),
                ('waist_circumference', models.FloatField(default=0.0, help_text='腰圍（公分）')),
                ('hip_circumference', models.FloatField(default=0.0, help_text='臀圍（公分）')),
                ('chest_circumference', models.FloatField(default=0.0, help_text='胸圍（公分）')),
                ('shoulder_circumference', models.FloatField(blank=True, help_text='肩围 (cm)', null=True)),
                ('upper_arm_circumference', models.FloatField(blank=True, help_text='上臂圍 (公分)', null=True)),
                ('lower_arm_circumference', models.FloatField(blank=True, help_text='下臂圍 (公分)', null=True)),
                ('thigh_circumference', models.FloatField(blank=True, help_text='大腿圍 (公分)', null=True)),
                ('calf_circumference', models.FloatField(blank=True, help_text='小腿圍 (公分)', null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general_fitness', 'General Fitness')], default='綜合健身', max_length=20)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='運動總時間')),
                ('manual_calories_burned', models.FloatField(blank=True, help_text='手動輸入的熱量消耗（大卡）', null=True)),
                ('calculated_calories_burned', models.FloatField(default=0.0, help_text='自動計算的熱量消耗（大卡）')),
                ('scheduled_date', models.DateField(help_text='運動計劃的安排日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise_type', models.ManyToManyField(blank=True, to='exercise.exercisetype')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('body_part', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body')], default='full_body', max_length=20)),
                ('joint_type', models.CharField(choices=[('single_joint', 'Single Joint'), ('multi_joint', 'Multi Joint')], default='multi_joint', max_length=20)),
                ('sets', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('actual_duration', models.PositiveIntegerField(help_text='Actual duration per set in seconds')),
                ('rest_time', models.PositiveIntegerField(help_text='Rest time between sets in seconds')),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exercise.exerciseset')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercises', models.ManyToManyField(to='exercise.exercise')),
            ],
        ),
    ]
