# Generated by Django 5.1.2 on 2024-10-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=20)),
                ('total_duration', models.PositiveIntegerField(help_text='Total duration in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('body_part', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body')], default='full_body', max_length=20)),
                ('sets', models.PositiveIntegerField()),
                ('reps_per_set', models.PositiveIntegerField()),
                ('duration_per_set', models.PositiveIntegerField(blank=True, help_text='Duration per set in minutes', null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight per rep in kg', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
    ]
