# Generated by Django 4.2.16 on 2024-11-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='goal',
            field=models.IntegerField(choices=[(1, 'Muscle Gain'), (2, 'Fat Loss'), (3, 'Endurance'), (4, 'Flexibility'), (5, 'General Fitness')], default=5),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='body_part',
            field=models.CharField(choices=[(1, 'Chest'), (2, 'Back'), (3, 'Legs'), (4, 'Shoulders'), (5, 'Arms'), (6, 'Core'), (7, 'Full Body')], default=7, max_length=20),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='joint_type',
            field=models.CharField(choices=[(1, 'Single Joint'), (2, 'Multi Joint')], default=2, max_length=20),
        ),
    ]
