# Generated by Django 5.1.2 on 2024-11-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_goal_alter_exerciseset_body_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='運動計劃的具體時間', null=True),
        ),
    ]
